application: emplementation
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /images
  static_dir: images

- url: /javascripts
  static_dir: javascripts
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /.*
  script: guestbook.py
